limb:
  version: 3.7.0.30
  listen_port: 22222
  hook_port: 22223

service:
  addr: ws://127.0.0.1:11111
  secret: "change-this-secret"
  ping_interval: 30s
  sync_delay: 1m
  sync_interval: 6h

log:
  level: info
